config/routes.rb
Rails.application.routes.draw do
  resources :answers,only:[:create]
  
  get "/questions/:id/solved"=>"questions#change_solved"
  get "/questions/:id/unsolved"=>"questions#change_unsolved" 
  
  get "/questions/solved" =>"questions#solved"
  get "/questions/unsolved"=>"questions#unsolved"

  namespace :admin do
    resources :questions,only:[:index,:destroy]
  end
  
  namespace :admin do
    get "/login",to:"sessions#new"
    post "/login",to:"sessions#create"
    delete "/logout",to:"sessions#destroy"
  end
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  
  resources :users,only:[:index,:new,:create]
  
  namespace :admin do
    resources :users,only:[:index, :destroy]
  end
  
  root to:'questions#index'
  resources :questions

end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :content,presence: true,length:{maximum:1000}
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title,presence: true,length:{maximum:50}
  validates :content,length:{maximum:1000}
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  validates :name, presence: true
  validates :email, uniqueness: true
  validates :password,length: { minimum: 6 }
  has_many :questions
  has_many :answers
  has_secure_password
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action:login_required
  before_action:admin_login_required
  
  def index
    @questions=Question.all
  end
  
  def destroy
    @question=Question.find(params[:id])
    @question.destroy
    redirect_to admin_questions_path,notice:"質問「#{@question.title}」を削除しました"
  end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  before_action:login_required,only:[:destroy]
  
  def new
  end

  def create
    user=User.find_by(email:session_params[:email])

    if user&.authenticate(session_params[:password]) && user.admin?
      session[:user_id]=user.id
      redirect_to "/admin/users",notice:'管理者権限でログインしました'
    else
      flash.now[:danger]="ログインに失敗しました"
      render :new
    end
  end

  def destroy
      reset_session
      redirect_to "/login",notice:"ログアウトしました"
  end

  private
  def session_params
    params.require(:session).permit(:email,:password)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action:login_required
  before_action:admin_login_required
  
  def index
    @users=User.all
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    flash[:notice]="ユーザー「#{@user.name}」を削除しました"
    redirect_to "/admin/users"
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action:login_required

  def create
    @question=Question.find(params[:answer][:question_id])
    @answer=Answer.new(answer_params.merge(user_id:current_user.id,question_id:@question.id))
    if @answer.save
      flash[:notice]="質問「#{@question.title}」に回答しました。"
      redirect_to @question 
    else
      flash[:danger]="回答が無効です"
      redirect_to @question
    end
  end
  
  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find_by(id:session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url,notice:'ログインが必要です' unless current_user
  end

  def admin_login_required
    redirect_to root_url,notice:"管理者権限が必要です" unless current_user.admin?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action:login_required
  before_action:correct_user,only:[:destroy,:edit,:update,:change_solved,:change_unsolved]
  
  def solved
    @questions=Question.where(solved:true)
  end

  def unsolved
    @questions=Question.where(solved:false)
  end

  def change_solved
    @question.update(solved: true)
    flash[:notice]="質問「#{@question.title}を解決済みにしました。」"
    redirect_to questions_path
  end
  
  def change_unsolved
    @question.update(solved: false)
    redirect_to questions_path
  end

  def index
    @q=Question.ransack(params[:q])
    @questions=@q.result(distinct: true).page(params[:page])

  end

  def show
    @question=Question.find(params[:id])
    @answers=@question.answers
    @answer=Answer.new
  end

  def new
    @question=Question.new
  end

  def edit
  end

  def create
    @question=current_user.questions.new(question_params)
    if @question.save
      redirect_to @question,notice:"質問「#{@question.title}」を投稿しました。"
      QuestionMailer.send_mail_users(current_user,@question)
    else
      render :new
    end
  end

  def update

    if @question.update(question_params)
      redirect_to @question,notice:"質問「#{@question.title}」を更新しました。"

    else
      render :edit
    end
  end

  def destroy
  
    @question.destroy
    redirect_to questions_url,notice:"質問「#{@question.title}」を削除しました。"
  end
  
  private

  def question_params
    params.require(:question).permit(:title,:content)
  end

  def correct_user
    @question = current_user.questions.find_by(id: params[:id])
    if @question.nil?
      flash[:danger]="権限がありません" 
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action:login_required,only:[:destroy]
  def new

  end

  def create
    user=User.find_by(email:session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id]=user.id
      redirect_to root_url,notice:'ログインしました'
    else
      flash.now[:danger]="ログインに失敗しました"
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to "/login",notice:"ログアウトしました"
  end

  private
  def session_params
    params.require(:session).permit(:email,:password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action:login_required,only:[:index]
  def index
    @users=User.all
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to users_path,notice:"Welcome to Q&A App!"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:image)
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/questions/index.html.slim
h1 質問一覧(管理者)

.mb-3
table.table.table-hover 
  thead.thead-default 
    tr 
      th= Question.human_attribute_name(:title)
      th= "状態"
      th= Question.human_attribute_name(:created_at)
      th
  tbody
    - @questions.each do |question|
      tr
        td= link_to question.title,"/questions/#{question.id}" 
        td= question.solved? ? "解決済み" : "未解決" 
        td= question.created_at

        td
          =link_to "削除","/admin/questions/#{question.id}",method: :delete,data:{confirm:"質問「#{question.title}」を削除します"},class:'btn btn-danger mr-3'

app/views/admin/users/index.html.slim
h1 ユーザ一覧(管理者)

.mb-3
table.table.table-hover 
  thead.thead-default 
    tr 
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= user.name
        td= user.email
        td= user.admin? ? "あり" : "なし"
        td= user.created_at
        td= user.updated_at
        td=link_to "削除","/admin/users/#{user.id}",method: :delete,data:{confirm:"ユーザー「#{user.name}」を削除します"},class:'btn btn-danger mr-3'
        
          

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Q&A App 
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light.mb-3
      .navbar-brand 
        =link_to "Q&A App",questions_path 

      ul.navbar-nav.ml-auto        
        - if current_user
          li.nav-item=link_to "ユーザ一覧",users_path,class:'nav-link'
          li.nav-item=link_to "質問一覧",questions_path,class:'nav-link'
          li.nav-item=link_to 'ログアウト',logout_path,method: :delete,class:'nav-link'
          li.nav-item=link_to "#{current_user.name}","#",class:'nav-link'
        - else 
          li.nav-item=link_to 'ログイン',login_path,class:'nav-link'
          li.nav-item=link_to '新規登録',new_user_path,class:'nav-link'
          li.nav-item=link_to '管理者',admin_login_path,class:'nav-link'
    .container.mb-3
      -if flash.notice.present?
        .alert.alert-success=flash.notice
      -elsif flash[:danger]
        .alert.alert-danger= flash[:danger] 
      = yield

-if current_user&.admin?
  footer.bg-light.text-center.text-lg-start
    .container.p-4
      .row
        .col-lg-6.col-md-12.mb-4.mb-md-0
          h5.text-uppercase
            | Administrator Menu
          p
            |  Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam voluptatem veniam, est atque cumque eum delectus sint! 
        .col-lg-3.col-md-6.mb-4.mb-md-0
          h5.text-uppercase
            | Users
          ul.list-unstyled.mb-0
            li
              a.text-dark[href="/admin/users"]
                | ユーザ一覧
            li
              a.text-dark[href="#!"]
                | Link 2
            li
              a.text-dark[href="#!"]
                | Link 3
            li
              a.text-dark[href="#!"]
                | Link 4
        .col-lg-3.col-md-6.mb-4.mb-md-0
          h5.text-uppercase
            | Questions
          ul.list-unstyled.mb-0
            li
              a.text-dark[href="/admin/questions"]
                | 質問一覧
            li
              a.text-dark[href="#!"]
                | Link 2
            li
              a.text-dark[href="#!"]
                | Link 3
            li
              a.text-dark[href="#!"]
                | Link 4
        
    .text-center.p-3[style="background-color: rgba(0, 0, 0, 0.2);"]
      |  © 2020 Copyright: 
      a.text-dark[href="https://mdbootstrap.com/"]
        | MDBootstrap.com

app/views/questions/_form.html.slim
- if object.errors.present?
  ul#error_explanation
    - object.errors.full_messages.each do |message|
      li =message

= form_with model:object,local: true do |f|
  .form-group
    =f.label :title 
    =f.text_field :title,class:'form-control',id:'question_title'
  .form-group 
    =f.label :content
    =f.text_area :content,rows: 5,class: 'form-control',id: 'question_content'
  =f.submit "質問する",class:'btn btn-primary'

app/views/questions/edit.html.slim
h1 質問の編集

.nav.justify-content-end 
  = link_to '一覧',questions_path,class:'nav-link'

= render partial: "form",locals: {object:@question}

app/views/questions/index.html.slim
h1 質問一覧

= link_to '質問する',new_question_path,class:'btn btn-primary'

.mb-3
table.table.table-hover 
  thead.thead-default 
    tr 
      th= Question.human_attribute_name(:title)
      th= "質問者"
      th= Question.human_attribute_name(:created_at)
      th
  tbody
    - @questions.each do |question|
      tr
        td= link_to question.title,"questions/#{question.id}" 
        td= question.user.name
        td= question.created_at

        td
          - if current_user.id==question.user_id
            =link_to "編集",edit_question_path(question),class:'btn btn-primary mr-3'
            =link_to "削除","/questions/#{question.id}",method: :delete,data:{confirm:"質問「#{question.title}」を削除します"},class:'btn btn-danger mr-3'

app/views/questions/new.html.slim
h1 質問する

.nav.justify-content-end
  = link_to '一覧',questions_path,class:'nav-link'

= render partial: "form",locals: {object:@question}

app/views/questions/show.html.slim
h1.mt-3.text-white.bg-dark.pl-2 質問の詳細

.nav.justfy-content-end
  = link_to '一覧' ,  questions_path, class:'nav-link'
table.table.table-hover 
  tbody
    tr 
      th.item=Question.human_attribute_name(:id)
      td=@question.id
    tr
      th=Question.human_attribute_name(:title)
      td=@question.title
    tr
      th="状態"
      td=@question.solved? ? "解決済み" : "未解決"

    tr
      th="質問者"
      td=@question.user.name
    tr
      th=Question.human_attribute_name(:content)
      td=simple_format(h(@question.content),{},santize:false,wrapper_tag:"div")
    tr
      / th=Task.human_attribute_name(:image)
      / td=image_tag @task.image if @task.image.attached?
    
    tr
      th=Question.human_attribute_name(:created_at)
      td=@question.created_at
    tr
      th=Question.human_attribute_name(:updated_at)
      td=@question.updated_at
-if current_user.id == @question.user_id
  = link_to '編集',"/questions/#{@question.id}/edit",class:'btn btn-primary mr-3'
  = link_to '削除',"/questions/#{@question.id}",method: :delete ,data:{confirm: "質問「#{@question.title}」を削除します。よろしいですか？"},class: 'btn btn-danger'

- unless @answers.count==0
  h1.mt-3.text-white.bg-dark.pl-2.mt-5 回答一覧

  table.table.table-hover 
    thead.thead-default 
      tr 
        th= "回答者"
        th= "内容"
        th= "回答日時"
        th
    tbody
      - @answers.each do |answer|
        tr
          td= answer.user.name
          td= simple_format(h(answer.content),{},santize:false,wrapper_tag:"div")
          td= answer.created_at

-unless @question.solved?
  
  h1.mt-3.text-white.bg-dark.pl-2.mt-5 回答する
  = form_with model:@answer,local: true do |f|
    .form-group 
      =f.label :content
      =f.text_area :content,rows: 5,class: 'form-control',id: 'question_content'
    = f.hidden_field :question_id, value:@question.id
    =f.submit "回答する",class:'btn btn-primary'

app/views/questions/solved.html.slim
=link_to "全ての質問",questions_path,class:'btn btn-info mr-3'
=link_to "解決済みの質問","/questions/solved",class:'btn btn-success mr-3'
=link_to "未解決の質問","/questions/unsolved",class:'btn btn-danger mr-3'

h1 質問一覧

= link_to '質問する',new_question_path,class:'btn btn-primary'

.mb-3
table.table.table-hover 
  thead.thead-default 
    tr 
      th= Question.human_attribute_name(:title)
      th= "状態"
      th= "質問者"
      th= Question.human_attribute_name(:created_at)
      th
  tbody
    - @questions.each do |question|
      tr
        td= link_to question.title,"questions/#{question.id}" 
        td= question.solved? ? "解決" : "未解決"
        td= question.user.name
        td= question.created_at

        td
          - if current_user.id==question.user_id
            =link_to "編集",edit_question_path(question),class:'btn btn-primary mr-3'
            =link_to "削除","/questions/#{question.id}",method: :delete,data:{confirm:"質問「#{question.title}」を削除します"},class:'btn btn-danger mr-3'
            - if question.solved? 
              =link_to "未解決にする","/questions/#{question.id}/unsolved",data:{confirm:"質問「#{question.title}」を未解決にします"},class:'btn btn-danger mr-3'
            - else
              =link_to "解決済みにする","/questions/#{question.id}/solved",data:{confirm:"質問「#{question.title}」を解決済みにします"},class:'btn btn-primary mr-3'

app/views/questions/unsolved.html.slim
=link_to "全ての質問",questions_path,class:'btn btn-info mr-3'
=link_to "解決済みの質問","/questions/solved",class:'btn btn-success mr-3'
=link_to "未解決の質問","/questions/unsolved",class:'btn btn-danger mr-3'

h1 質問一覧

= link_to '質問する',new_question_path,class:'btn btn-primary'

.mb-3
table.table.table-hover 
  thead.thead-default 
    tr 
      th= Question.human_attribute_name(:title)
      th= "状態"
      th= "質問者"
      th= Question.human_attribute_name(:created_at)
      th
  tbody
    - @questions.each do |question|
      tr
        td= link_to question.title,"questions/#{question.id}" 
        td= question.solved? ? "解決" : "未解決"
        td= question.user&.name
        td= question.created_at

        td
          - if current_user.id==question.user_id
            =link_to "編集",edit_question_path(question),class:'btn btn-primary mr-3'
            =link_to "削除","/questions/#{question.id}",method: :delete,data:{confirm:"質問「#{question.title}」を削除します"},class:'btn btn-danger mr-3'
            - if question.solved? 
              =link_to "未解決にする","/questions/#{question.id}/unsolved",data:{confirm:"質問「#{question.title}」を未解決にします"},class:'btn btn-danger mr-3'
            - else
              =link_to "解決済みにする","/questions/#{question.id}/solved",data:{confirm:"質問「#{question.title}」を解決済みにします"},class:'btn btn-primary mr-3'

app/views/users/index.html.slim
h1 ユーザ一覧

.mb-3
table.table.table-hover
  thead.thead-default
    tr 
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= "アバター画像"

      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
  tbody
    - @users.each do |user|
      tr
        td= user.name
        td= user.email
        td= image_tag user.image if user.image.attached?

        td= user.created_at
        td= user.updated_at

app/views/users/new.html.slim
h1 ユーザー登録
- if @user.errors.present?
  ul#error_explanation
    - @user.errors.full_messages.each do |message|
      li =message

= form_with model:@user,local: true do |f|
  .form-group
    =f.label :name 
    =f.text_field :name,class:'form-control',id:'user_name'
  .form-group 
    =f.label :email
    =f.text_field :email,class: 'form-control',id: 'user_email'
  .form-group 
    =f.label :password
    =f.password_field :password,class: 'form-control',id: 'user_password'
  .form-group 
    =f.label :password_confirmation
    =f.password_field :password_confirmation,class: 'form-control',id: 'user_password_confirmation'
  .form-group
    =f.label :image
    =f.file_field :image,class: 'form-control'
  
  =f.submit "新規登録",class:'btn btn-primary'